=== orb1t/juel/project/doc/schema/dtd/project.dtd
<!--
 ! Copyright 2004 Odysseus Software GmbH
 !
 ! Licensed under the Apache License, Version 2.0 (the "License");
 ! you may not use this file except in compliance with the License.
 ! You may obtain a copy of the License at
 !
 !     http://www.apache.org/licenses/LICENSE-2.0
 !
 ! Unless required by applicable law or agreed to in writing, software
 ! distributed under the License is distributed on an "AS IS" BASIS,
 ! WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 ! See the License for the specific language governing permissions and
 ! limitations under the License.
 !-->
<!ENTITY % common-charents PUBLIC
    "-//APACHE//ENTITIES Common Character Entity Sets V1.0//EN"
    "common-charents-v10.mod">
%common-charents;

<!-- element declarations -->
<!ELEMENT project     (title?,item?,(document|group|link|external-ref)+)>
<!ATTLIST project
    name    NMTOKEN   #REQUIRED
    index   NMTOKEN   #IMPLIED
>

<!ELEMENT title       (#PCDATA)>

<!ELEMENT document    (item?)>
<!ATTLIST document
    name    NMTOKEN   #REQUIRED
    includes NMTOKENS #IMPLIED
    excludes NMTOKENS #IMPLIED
>

<!ELEMENT link        (item)>
<!ATTLIST link
    href    CDATA     #REQUIRED
    target  NMTOKEN   #IMPLIED
    includes NMTOKENS #IMPLIED
    excludes NMTOKENS #IMPLIED
>

<!ELEMENT group       (title?,item,(document|group|link)+)>
<!ATTLIST group
    name    NMTOKEN   #REQUIRED
    dir     CDATA     #IMPLIED
    index   CDATA     #IMPLIED
    includes NMTOKENS #IMPLIED
    excludes NMTOKENS #IMPLIED
>

<!ELEMENT item        (#PCDATA)>

<!ELEMENT external-ref EMPTY>
<!ATTLIST external-ref
    name    NMTOKEN   #REQUIRED
    href    CDATA     #REQUIRED
>

=== orb1t/juel/project/doc/project.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE project PUBLIC "-//Odysseus Software GmbH//DTD Forrester Project 1.0//EN" "./schema/dtd/project.dtd">

<project name="juel" index="index">
	<title>Java Unified Expression Language</title>
	<item>JUEL</item>

	<document name="index" excludes="pdf"/>
	<document name="index" includes="pdf">
		<item>Intro</item>
	</document>

	<group name="guide" dir="guide" index="index">
		<item>Guide</item>
		<document name="index"/>

		<document name="start">
			<item>Quickstart</item>
		</document>

		<group name="basic" dir="basic" index="index">
			<item>Basic Classes</item>
			<document name="index"/>
			<document name="factory">
				<item>Expression Factory</item>
			</document>
			<document name="value">
				<item>Value Expressions</item>
			</document>
			<document name="method">
				<item>Method Expressions</item>
			</document>
		</group>

		<group name="util" dir="util" index="index">
			<item>Utility Classes</item>
			<document name="index"/>
			<document name="context">
				<item>Simple Context</item>
			</document>
			<document name="resolver">
				<item>Simple Resolver</item>
			</document>
		</group>

		<document name="service">
			<item>Plugin JUEL</item>
		</document>

		<group name="advanced" dir="advanced" index="index">
			<item>Advanced Topics</item>
			<document name="index"/>
		</group>

		<document name="issues">
			<item>Specification Issues</item>
		</document>
	</group>

	<group name="project" dir="project">
		<title>JUEL Project</title>
		<item>Project</item>
		<link href="site://api/index.html" target="_blank" excludes="site pdf">
			<item>API Documentation</item>
		</link>
		<document name="changes">
			<item>History of Changes</item>
		</document>
	</group>

  <external-ref name="apache.org.license" href="http://www.apache.org/licenses/LICENSE-2.0"/>
  <external-ref name="sun.com.license" href="https://glassfish.dev.java.net/public/CDDLv1.0.html"/>
  <external-ref name="uel.dev.java.net" href="https://uel.dev.java.net/"/>
  <external-ref name="jcp.com.jsr245" href="http://jcp.org/aboutJava/communityprocess/final/jsr245/"/>
</project>
